version: '3.8'  

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "yarn dev"
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "3000:3000" 

  